### ISSUE TITLE
install error with "ActionView::Template::Error (Missing partial app_notifications"

### ISSUE THREAD

**Issue by sword588** [MichalVanzura/redmine_app_notifications#22]
Hi,
I have installed this plugin with my 2.6.0 redmine and after restart the web server I got the following error in the log file. Would you please let me know how to solve this issue?
Any help is really appreciated.

ActionView::Template::Error (Missing partial app_notifications/layouts_base_html_head with {:locale=>[:zh, :en], :formats=>[:html], :handlers=>[:erb, :builder, :rsb]}. Searched in:
  * "/var/www/html/redmine/plugins/advanced_roadmap_v2/app/views"
  * "/var/www/html/redmine/app/views"
):
    11: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    12: <%= javascript_heads %>
    13: <%= heads_for_theme %>
    14: <%= call_hook :view_layouts_base_html_head %>
    15: 
    16: <%= yield :header_tags -%>
    17: </head>
  lib/redmine/hook.rb:111:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in `call_hook'
  app/views/layouts/base.html.erb:14:in `_app_views_layouts_base_html_erb___2866693996775738177_70155095022520'
  app/controllers/application_controller.rb:465:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:463:in `render_error'
  app/controllers/application_controller.rb:451:in `render_404'
  app/controllers/application_controller.rb:475:in `missing_template'

**Comment by Androc** [comment]
Hello,

* did you try to install several plugins at once ?
* did you correctly installed the plugin (run the rake command at the top level of your Redmine installation) ?
* do you have a specific language you use instead of english ?

When I see "missing_template", "missing partial", etc. I think it is about permissions or missing files.

**Comment by sword588** [comment]
Thanks for your quick reply. Here're the answers to your questions.
1. did you try to install several plugins at once ?
yes. 
2. did you correctly installed the plugin (run the rake command at the top level of your Redmine installation) ?
yes. 
3. do you have a specific language you use instead of english ?
Yes, I am using chinese. 
4. When I see "missing_template", "missing partial", etc. I think it is about permissions or missing files.
What specific permission do I need to configure?

**Comment by Androc** [comment]
I was thinking about files permissions.
But it is more a problem of language, I suppose ```Missing partial app_notifications/layouts_base_html_head with {:locale=>[:zh, :en], :formats=>[:html], :handlers=>[:erb, :builder, :rsb]}```

**Comment by Androc** [comment]
What is strange is ```app_notifications/layouts_base_html_head```.
Did you extract the plugin into ```[redmine_root]/plugins/redmine_app_notifications``` ?

Do you have a file ```_layouts_base_html_head.html.erb``` in ```app/views``` of your plugin ?

**Comment by sword588** [comment]
I extracted it to directory app_notifications. 
Yes, _layouts_base_html_head.html.erb is in app/views.

**Comment by Androc** [comment]
Uninstall it then try to install it in ```[redmine_root]/plugins/redmine_app_notifications```
