### ISSUE TITLE
Redmine 4.2 NoMethodError on Issue update

### ISSUE THREAD

**Issue by alterdaemon** [MichalVanzura/redmine_app_notifications#38]
Completed 500 Internal Server Error in 490ms (ActiveRecord: 119.2ms)

NoMethodError (undefined method `parse_mentions' for #<Journal:0x00007f8acaf001c0>):

plugins/redmine_app_notifications/lib/app_notifications_journals_patch.rb:38:in `create_app_notifications_after_create_journal'
app/models/journal.rb:100:in `save'
app/models/issue.rb:1993:in `create_journal'
app/models/issue.rb:227:in `create_or_update'
app/controllers/issues_controller.rb:629:in `block in save_issue_with_child_records'
app/controllers/issues_controller.rb:610:in `save_issue_with_child_records'
app/controllers/issues_controller.rb:190:in `update'
lib/redmine/sudo_mode.rb:61:in `sudo_mode'

**Comment by alterdaemon** [comment]
wrong repo
